config/routes.rb
Rails.application.routes.draw do
  get 'pipeline/pipeline'
  get 'pipeline' => 'pipeline#pipeline'
  root 'pipeline#pipeline'

  get 'plant_group_updates/transplant_to_veg' => 'plant_group_updates#transplant_to_veg'
  get 'plant_group_updates/transplant_to_flower' => 'plant_group_updates#transplant_to_flower'
  get 'plant_group_updates/flip' => 'plant_group_updates#flip'
  get 'plant_group_updates/modify_quantity' => 'plant_group_updates#modify_quantity'
  resources :plant_group_updates

  resources :plant_groups
  resources :rooms


  get 'debug/index'
  get 'debug' => 'debug#index'
  get 'debug/search'
end

app/models/plant_group.rb
class PlantGroup < ApplicationRecord
	has_many :plant_group_updates, dependent: :destroy

	validates :quantity, :nickname, :current_room_id, :clone_date, presence: true
	after_create :create_clone_update



	private
	def create_clone_update
		PlantGroupUpdate.create!(plant_group: self, update_type: "clone", quantity: self.quantity, transplant_destination_room_id: self.current_room_id, transplant_origin_room_id: self.current_room_id)
	end
end

app/controllers/plant_groups_controller.rb
class PlantGroupsController < ApplicationController
  before_action :set_plant_group, only: [:show, :edit, :update, :destroy]

  # GET /plant_groups
  # GET /plant_groups.json
  def index
    @plant_groups = PlantGroup.all
    @rooms = Room.all
    @update_types = ["clone","transplant to veg","transplant to flower","flip","modify quantity","harvest"]
  end

  # GET /plant_groups/1
  # GET /plant_groups/1.json
  def show
    @rooms = Room.all
  end

  # GET /plant_groups/new
  def new
    @plant_group = PlantGroup.new
  end

  # GET /plant_groups/1/edit
  def edit
  end

  # POST /plant_groups
  # POST /plant_groups.json
  def create
    @plant_group = PlantGroup.new(plant_group_params)

    respond_to do |format|
      if @plant_group.save
        format.html { redirect_to @plant_group, notice: 'Plant group was successfully created.' }
        format.json { render :show, status: :created, location: @plant_group }
      else
        format.html { render :new }
        format.json { render json: @plant_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /plant_groups/1
  # PATCH/PUT /plant_groups/1.json
  def update
    respond_to do |format|
      if @plant_group.update(plant_group_params)
        format.html { redirect_to @plant_group, notice: 'Plant group was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant_group }
      else
        format.html { render :edit }
        format.json { render json: @plant_group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plant_groups/1
  # DELETE /plant_groups/1.json
  def destroy
    @plant_group.destroy
    respond_to do |format|
      format.html { redirect_to plant_groups_url, notice: 'Plant group was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant_group
      @plant_group = PlantGroup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_group_params
      params.require(:plant_group).permit(:nickname, :quantity, :clone_date, :current_room_id, :notes)
    end
end

app/helpers/plant_groups_helper.rb
module PlantGroupsHelper
end

app/views/plant_groups/_form.html.erb
<%= form_for(plant_group) do |f| %>
  <% if plant_group.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plant_group.errors.count, "error") %> prohibited this plant_group from being saved:</h2>

      <ul>
      <% plant_group.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.text_field :quantity, :value => 100 %>
  </div>

  <div class="field">
    <%= f.label :nickname %>
    <%= f.text_field :nickname %>
  </div>

  <div class="field">
    <%= f.label :clone_date %>
    <%= f.text_field :clone_date, :value => Date.today %>
  </div>

  <div class="field">
    <%= f.label :current_room_id %>
    <%= f.collection_select :current_room_id, Room.order(:id),:id,:name %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_field :notes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plant_groups/edit.html.erb
<h1>Editing Plant Group</h1>

<%= render 'form', plant_group: @plant_group %>

<%= link_to 'Show', @plant_group %> |
<%= link_to 'Back', plant_groups_path %>

app/views/plant_groups/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plant Groups</h1>

<hr>

<table width="100%">
  <tr>
    <% @plant_groups.column_names.each{|columnhead| %>
      <th><%= columnhead %></th>
    <% } %>
      <th></th>
  </tr>
  <% @plant_groups.each{|pg| %>
  <tr>
    <td><%= pg.id %></td>
    <td><%= pg.nickname %></td>
    <td><%= pg.quantity %></td>
    <td><%= pg.clone_date %></td>
    <td><%= pg.current_room_id %></td>
    <td><%= pg.notes %></td>
    <td><%= pg.created_at.hour %>:<%= pg.created_at.min %> -- <%= pg.created_at.month %>/<%= pg.created_at.day %>/<%= pg.created_at.year %></td>
    <td><%= pg.updated_at.hour %>:<%= pg.updated_at.min %>  -- <%= pg.updated_at.month %>/<%= pg.updated_at.day %>/<%= pg.updated_at.year %></td>
    <td>
      <div class="dropdown" style="margin:6px;">
        <button class="btn btn-success dropdown-toggle" type="button" data-toggle="dropdown">Update <%= pg.nickname %> PlantGroup
        <span class="caret"></span></button>
        <ul class="dropdown-menu">
          <li>
            <%= link_to 'Transplant to Veg', plant_group_updates_transplant_to_veg_path(:controller => "pg_updates", :action => "transplant_to_veg", :group => pg.id) %>
          </li>
          <li>
            <%= link_to 'Transplant to Flower', plant_group_updates_transplant_to_flower_path(:controller => "pg_updates", :action => "transplant_to_flower", :group => pg.id) %>
          </li>
          <li><%= link_to 'Flip', plant_group_updates_flip_path(:controller => "pg_updates", :action => "flip", :group => pg.id) %></li>
          <li><%= link_to 'Modify Quantity', plant_group_updates_modify_quantity_path(:controller => "pg_updates", :action => "modify_quantity", :group => pg.id) %></li>
          <li>
            <%= link_to 'Harvest', pg %>
          </li>
          <li>
            <%= link_to 'Destroy', pg, method: :delete, data: { confirm: 'Are you sure?' } %>
          </li>
        </ul>
      </div>      
    </td>
  </tr>
  <% } %>
</table>

<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<br><br>
<p align="center"><i>ignore below</i></p>
<hr>
<table width="100%">
  <tr>
      <th>Nickname</th>
      <th>CurrentQuantity</th>
      <th>CurrentRoom</th>
      <th>MostRecentAction</th>
      <th>NextAction</th>
      <th>PotSize</th>
      <th>CloneDate</th>
      <th>Notes</th>
  </tr>
  <tr>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
    <td></td>
  </tr>
</table>

app/views/plant_groups/new.html.erb
<h1>New Plant Group</h1>

<%= render 'form', plant_group: @plant_group %>

<%= link_to 'Back', plant_groups_path %>

app/views/plant_groups/show.html.erb
<p id="notice"><%= notice %></p>



<table>
  <tr>
    <td style="border-right-width: 1px; border-right-style: solid">
      <p align="center"><strong>Overview</strong></p>
      <p>
        <strong>Quantity:</strong>
        <%= @plant_group.quantity %>
      </p>

      <p>
        <strong>Nickname:</strong>
        <%= @plant_group.nickname %>
      </p>

      <p>
        <strong>Current Room:</strong>
        <%= @rooms.where(id: @plant_group.current_room_id)[0].name %>
      </p>

      <p>
        <strong>Clone_date:</strong>
        <%= @plant_group.clone_date %>
      </p>

      <p>
        <strong>Notes:</strong>
        <%= @plant_group.notes %>
      </p>

      <p>
      <hr>
      <%= link_to 'Edit', edit_plant_group_path(@plant_group) %> |
<%= link_to 'Back', plant_groups_path %>
      </p>
    </td>
    <td>
    <p align="center"><strong>Updates</strong></p>
    <ul>
      <% @plant_group.plant_group_updates.each{|pgu| %>
        <li>
          <%= pgu.update_type %>, <%= pgu.quantity %>, <%= pgu.updated_at %>
        </li>
      <% } %>
      </ul>
      <p align="center">
      <hr>
        
        <a href="/">Transplant to Veg</a> |
        <a href="/">Transplant to Flower</a> |
        <a href="/">Flip</a>
      </p>
    </td>
  </tr>
</table>