config/routes.rb
Rails.application.routes.draw do
  get 'pipeline/pipeline'
  get 'pipeline' => 'pipeline#pipeline'
  root 'pipeline#pipeline'

  get 'plant_group_updates/transplant_to_veg' => 'plant_group_updates#transplant_to_veg'
  get 'plant_group_updates/transplant_to_flower' => 'plant_group_updates#transplant_to_flower'
  get 'plant_group_updates/flip' => 'plant_group_updates#flip'
  get 'plant_group_updates/modify_quantity' => 'plant_group_updates#modify_quantity'
  resources :plant_group_updates

  resources :plant_groups
  resources :rooms


  get 'debug/index'
  get 'debug' => 'debug#index'
  get 'debug/search'
end

app/models/plant_group_update.rb
class PlantGroupUpdate < ApplicationRecord
	has_one :room
	belongs_to :plant_group

	validates :plant_group, :update_type, :quantity, presence: true

	after_create :update_plant_group
	#after_destroy :update_plant_group

	private
	def update_plant_group
		@pg = self.plant_group
		@pg.update!(:current_room_id => self.transplant_destination_room_id, :quantity => self.quantity)
	end
end

app/controllers/plant_group_updates_controller.rb
class PlantGroupUpdatesController < ApplicationController
  before_action :set_plant_group_update, only: [:show, :edit, :update, :destroy]

  # GET /plant_group_updates
  # GET /plant_group_updates.json
  def index
    @plant_group_updates = PlantGroupUpdate.all
  end

  # GET /plant_group_updates/1
  # GET /plant_group_updates/1.json
  def show
  end

  # GET /plant_group_updates/new
  def new
    @plant_group_update = PlantGroupUpdate.new
    #@plant_group_update = PlantGroupUpdate.new(params[:plant_group_update])
    #@plant_group = PlantGroup.find(params[:plant_group_id])
  end

  # GET /plant_group_updates/1/edit
  def edit
  end

  # POST /plant_group_updates
  # POST /plant_group_updates.json
  def create
    @plant_group_update = PlantGroupUpdate.new(plant_group_update_params)

    respond_to do |format|
      if @plant_group_update.save
        format.html { redirect_to @plant_group_update, notice: 'Plant group update was successfully created.' }
        format.json { render :show, status: :created, location: @plant_group_update }
      else
        format.html { render :new }
        format.json { render json: @plant_group_update.errors, status: :unprocessable_entity }
      end
    end

#  @plant_group_update = PlantGroupUpdate.new(params[:plant_group_update])
#  @plant_group_update.plant_group = PlantGroup.find(params[:project_id])
#  @plant_group_update.save
  end

  # PATCH/PUT /plant_group_updates/1
  # PATCH/PUT /plant_group_updates/1.json
  def update
    respond_to do |format|
      if @plant_group_update.update(plant_group_update_params)
        format.html { redirect_to @plant_group_update, notice: 'Plant group update was successfully updated.' }
        format.json { render :show, status: :ok, location: @plant_group_update }
      else
        format.html { render :edit }
        format.json { render json: @plant_group_update.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /plant_group_updates/1
  # DELETE /plant_group_updates/1.json
  def destroy
    @plant_group_update.destroy
    respond_to do |format|
      format.html { redirect_to plant_group_updates_url, notice: 'Plant group update was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

#  def transplant
#    @plant_group = PlantGroup.find(params[:id])
#    if @plant_group.update(plant_group_params)
#      redirect_to(@plant_group)
#    else
#     render "plant_group_updates/transplant"
#    end
#  end

  def transplant_to_veg
    @plant_group = PlantGroup.find(params[:group])
    @new_plant_group_update = PlantGroupUpdate.new
  end

  def transplant_to_flower
    @plant_group = PlantGroup.find(params[:group])
    @new_plant_group_update = PlantGroupUpdate.new
  end

  def flip
    @plant_group = PlantGroup.find(params[:group])
    @new_plant_group_update = PlantGroupUpdate.new
  end

  def modify_quantity
    @plant_group = PlantGroup.find(params[:group])
    @new_plant_group_update = PlantGroupUpdate.new
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_plant_group_update
      @plant_group_update = PlantGroupUpdate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def plant_group_update_params
      params.require(:plant_group_update).permit(:plant_group_id, :update_type, :quantity, :transplant_origin_room_id, :transplant_destination_room_id, :notes, :pot_size)
    end

#    def set_plant_group
#      @plant_group = PlantGroup.find(params[:group])
#    end
end

app/helpers/plant_group_updates_helper.rb
module PlantGroupUpdatesHelper
end

app/views/plant_group_updates/_flip.html.erb
<%= form_for(@new_plant_group_update) do |f| %>
  <% if @new_plant_group_update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@new_plant_group_update.errors.count, "error") %> prohibited this @new_plant_group_update from being saved:</h2>

      <ul>
      <% @new_plant_group_update.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td>
        <div class="field">
          <%= f.label :update_type %>
          <%= f.select :update_type, options_for_select(["clone","transplant","flip","harvest"], :selected => "flip") %>
        </div>        
      </td>
      <td>
        <div class="field">
          <%= f.label :plant_group_id %>
          <%= f.collection_select :plant_group_id, PlantGroup.order(:created_at),:id,:nickname, :selected => @plant_group.id %>
        </div>
      </td>
      <td>
        <div class="field">
          <%= f.label :transplant_origin_room_id %>
          <%= f.collection_select :transplant_origin_room_id, Room.order(:created_at),:id,:name, :selected => @plant_group.current_room_id %>
        </div>
      </td>
      <td>
      <div class="field">
          <%= f.label :transplant_destination_room_id %>
          <%= f.collection_select :transplant_destination_room_id, Room.order(:created_at),:id,:name, :selected => @plant_group.current_room_id %>
        </div>
      </td>
      <td>
        <div class="field">
          <%= f.label :quantity %>
          <%= f.text_field :quantity, :value => @plant_group.quantity %>
        </div>
      </td>
    </tr>
  </table>

  <table>
    <tr>
      <td>
        <div class="field">
          <%= f.label :date %>
          <%= f.date_field :created_at, :value => Date.today %>
        </div>
      </td>
      <td>
        <div class="field">
          <%= f.label :notes %>
          <%= f.text_field :notes %>
        </div>
      </td>
    </tr>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plant_group_updates/_form.html.erb
<%= form_for(plant_group_update) do |f| %>
  <% if plant_group_update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(plant_group_update.errors.count, "error") %> prohibited this plant_group_update from being saved:</h2>

      <ul>
      <% plant_group_update.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :plant_group_id %>
    <%= f.collection_select :plant_group_id, PlantGroup.order(:created_at),:id,:nickname %>
  </div>

  <div class="field">
    <%= f.label :update_type %>
    <%= f.select :update_type, options_for_select(["clone","transplant","flip","harvest"]), include_blank: true %>
  </div>

  <div class="field">
    <%= f.label :quantity %>
    <%= f.text_field :quantity %>
  </div>

  <div class="field">
    <%= f.label :transplant_origin_room_id %>
    <%= f.collection_select :transplant_origin_room_id, Room.order(:created_at),:id,:name %>
  </div>

  <div class="field">
    <%= f.label :transplant_destination_room_id %>
    <%= f.collection_select :transplant_destination_room_id, Room.order(:created_at),:id,:name %>
  </div>

  <div class="field">
    <%= f.label :notes %>
    <%= f.text_field :notes %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plant_group_updates/_modify_quantity.html.erb
<%= form_for(@new_plant_group_update) do |f| %>
  <% if @new_plant_group_update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@new_plant_group_update.errors.count, "error") %> prohibited this @new_plant_group_update from being saved:</h2>

      <ul>
      <% @new_plant_group_update.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td>
        <div class="field">
          <%= f.label :update_type %>
          <%= f.select :update_type, options_for_select(["clone","transplant","flip","modify quantity","harvest"], :selected => "modify quantity") %>
        </div>        
      </td>
      <td>
        <div class="field">
          <%= f.label :plant_group_id %>
          <%= f.collection_select :plant_group_id, PlantGroup.order(:created_at),:id,:nickname, :selected => @plant_group.id %>
        </div>
      </td>
    </tr>
  </table>

  <hr>

  <table>
     <tr> 
      <td>
        <div class="field">
          <%= f.label :quantity %>
          <%= f.text_field :quantity, :value => @plant_group.quantity %>
        </div>
      </td>
    </tr>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plant_group_updates/_transplant.html.erb
<%= form_for(@new_plant_group_update) do |f| %>
  <% if @new_plant_group_update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@new_plant_group_update.errors.count, "error") %> prohibited this @new_plant_group_update from being saved:</h2>

      <ul>
      <% @new_plant_group_update.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td>
        <div class="field">
          <%= f.label :update_type %>
          <%= f.select :update_type, options_for_select(["clone","transplant","flip","harvest"], :selected => "transplant") %>
        </div>        
      </td>
      <td>
        <div class="field">
          <%= f.label :plant_group_id %>
          <%= f.collection_select :plant_group_id, PlantGroup.order(:created_at),:id,:nickname, :selected => @plant_group.id %>
        </div>
      </td>
      <td>
        <div class="field">
          <%= f.label :transplant_origin_room_id %>
          <%= f.collection_select :transplant_origin_room_id, Room.order(:created_at),:id,:name, :selected => @plant_group.current_room_id %>
        </div>
      </td>
    </tr>
  </table>

  <table>
    <tr>
      <td>
        <div class="field">
          <%= f.label :quantity %>
          <%= f.text_field :quantity, :value => @plant_group.quantity %>
        </div>
      </td>
      <td>
      <div class="field">
          <%= f.label :transplant_destination_room_id %>
          <%= f.collection_select :transplant_destination_room_id, Room.order(:created_at),:id,:name, include_blank: true %>
        </div>
      </td>
      <td>
        <div class="field">
          <%= f.label :notes %>
          <%= f.text_field :notes %>
        </div>
      </td>
    </tr>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plant_group_updates/_transplant_to_flower.html.erb
<%= form_for(@new_plant_group_update) do |f| %>
  <% if @new_plant_group_update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@new_plant_group_update.errors.count, "error") %> prohibited this @new_plant_group_update from being saved:</h2>

      <ul>
      <% @new_plant_group_update.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td>
        <div class="field">
          <%= f.label :update_type %>
          <%= f.select :update_type, options_for_select(["clone","transplant to veg","transplant to flower","flip","harvest"], :selected => "transplant to flower") %>
        </div>        
      </td>
      <td>
        <div class="field">
          <%= f.label :plant_group_id %>
          <%= f.collection_select :plant_group_id, PlantGroup.order(:created_at),:id,:nickname, :selected => @plant_group.id %>
        </div>
      </td>
      <td>
        <div class="field">
          <%= f.label :transplant_origin_room_id %>
          <%= f.collection_select :transplant_origin_room_id, Room.order(:created_at),:id,:name, :selected => @plant_group.current_room_id %>
        </div>
      </td>
    </tr>
  </table>

<hr>

  <table>
    <tr>
      <td>
        <div class="field">
          <%= f.label :date %>
          <%= f.date_field :date_created, :value => Date.today %>
        </div>
      </td>
      <td>
      <div class="field">
          <%= f.label :destination_room %>
          <%= f.collection_select :transplant_destination_room_id, Room.order(:created_at),:id,:name, include_blank: true %>
        </div>
      </td>
      <td>
        <div class="field">
          <%= f.label :quantity %>
          <%= f.text_field :quantity, :value => @plant_group.quantity %>
        </div>
      </td>
      <td>
        <div class="field">
          <%= f.label :notes %>
          <%= f.text_field :notes %>
        </div>
      </td>
    </tr>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plant_group_updates/_transplant_to_veg.html.erb
<%= form_for(@new_plant_group_update) do |f| %>
  <% if @new_plant_group_update.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@new_plant_group_update.errors.count, "error") %> prohibited this @new_plant_group_update from being saved:</h2>

      <ul>
      <% @new_plant_group_update.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table>
    <tr>
      <td>
        <div class="field">
          <%= f.label :update_type %>
          <%= f.select :update_type, options_for_select(["clone","transplant to veg","transplant to flower","flip","harvest"], :selected => "transplant to veg") %>
        </div>        
      </td>
      <td>
        <div class="field">
          <%= f.label :plant_group_id %>
          <%= f.collection_select :plant_group_id, PlantGroup.order(:created_at),:id,:nickname, :selected => @plant_group.id %>
        </div>
      </td>
      <td>
        <div class="field">
          <%= f.label :transplant_origin_room_id %>
          <%= f.collection_select :transplant_origin_room_id, Room.order(:created_at),:id,:name, :selected => @plant_group.current_room_id %>
        </div>
      </td>
    </tr>
  </table>

<hr>

  <table>
    <tr>
      <td>
      <div class="field">
          <%= f.label :destination_room %>
          <%= f.collection_select :transplant_destination_room_id, Room.order(:created_at),:id,:name, include_blank: true %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <%= f.label :pot_size %>
          <%= f.select :pot_size, options_for_select(["3 inch","6 inch"], include_blank: true) %>
        </div>
      </td>
    </tr>      
    <tr>
      <td>
        <div class="field">
          <%= f.label :date %>
          <%= f.date_field :date_created, :value => Date.today %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <%= f.label :quantity %>
          <%= f.text_field :quantity, :value => @plant_group.quantity %>
        </div>
      </td>
    </tr>
    <tr>
      <td>
        <div class="field">
          <%= f.label :notes %>
          <%= f.text_field :notes %>
        </div>
      </td>
    </tr>
  </table>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/plant_group_updates/edit.html.erb
<h1>Editing Plant Group Update</h1>

<%= render 'form', plant_group_update: @plant_group_update %>

<%= link_to 'Show', @plant_group_update %> |
<%= link_to 'Back', plant_group_updates_path %>

app/views/plant_group_updates/flip.html.erb
<h1>Flip Seed Group</h1>

<%= render 'flip' %>

<hr>

app/views/plant_group_updates/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Plant Group Updates</h1>

<table>
  <thead>
    <tr>
      <th>Plant group</th>
      <th>Update type</th>
      <th>Quantity</th>
      <th>Transplant origin room</th>
      <th>Transplant destination room</th>
      <th>Notes</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @plant_group_updates.each do |plant_group_update| %>
      <tr>
        <td><%= plant_group_update.plant_group_id %></td>
        <td><%= plant_group_update.update_type %></td>
        <td><%= plant_group_update.quantity %></td>
        <td><%= plant_group_update.transplant_origin_room_id %></td>
        <td><%= plant_group_update.transplant_destination_room_id %></td>
        <td><%= plant_group_update.notes %></td>
        <td><%= link_to 'Show', plant_group_update %></td>
        <td><%= link_to 'Edit', edit_plant_group_update_path(plant_group_update) %></td>
        <td><%= link_to 'Destroy', plant_group_update, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Plant Group Update', new_plant_group_update_path %>

app/views/plant_group_updates/modify_quantity.html.erb
<h1>Modify Seed Group Quantity</h1>

<%= render 'modify_quantity' %>

<hr>

app/views/plant_group_updates/new.html.erb
<h1>New Plant Group Update</h1>

<%= render 'form', plant_group_update: @plant_group_update %>

<%= link_to 'Back', plant_group_updates_path %>

app/views/plant_group_updates/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Plant group:</strong>
  <%= @plant_group_update.plant_group_id %>
</p>

<p>
  <strong>Update type:</strong>
  <%= @plant_group_update.update_type %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @plant_group_update.quantity %>
</p>

<p>
  <strong>Transplant origin room:</strong>
  <%= @plant_group_update.transplant_origin_room_id %>
</p>

<p>
  <strong>Transplant destination room:</strong>
  <%= @plant_group_update.transplant_destination_room_id %>
</p>

<p>
  <strong>Notes:</strong>
  <%= @plant_group_update.notes %>
</p>

<%= link_to 'Edit', edit_plant_group_update_path(@plant_group_update) %> |
<%= link_to 'Back', plant_group_updates_path %>

app/views/plant_group_updates/transplant_to_flower.html.erb
<h1>Transplant to Flower</h1>

<%= render 'transplant_to_flower' %>

<hr>

app/views/plant_group_updates/transplant_to_veg.html.erb
<h1>Transplant to Veg</h1>

<%= render 'transplant_to_veg' %>

<hr>